### ISSUE TITLE
Display bug (Pixel 3 XL)

### ISSUE THREAD

**Issue by culcube** [qqzm/onerandomword#1]
Minor display issue with the first word displayed when it's a long word.
The first word it generated appears as "reimbursemen" (with the n chopped in half) in portrait mode and "reimbursement) (with the t chopped off) in landscape mode on a Pixel 3 XL.

Generating new words got some long words appearing correctly, e.g. circumference, and others having issues, e.g. "Championship" (with the p cut in half) in portrait and "Championships" (with the s cut in half) of Euro Championships (two lines).

**Comment by qqzm** [comment]
I believe this is fixed.
